<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="aewaec" Id="{56e7f148-eb2d-43cc-bcdf-15eea7cd4097}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK aewaec
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="aewaec">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>