<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="F_Concat6_Large" Id="{3877e970-03ef-4a02-a195-62ac08a0495d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat6_Large : STRING(StringsParams.MAX_STRING_LENGTH)
VAR_IN_OUT CONSTANT
	sOne : STRING(StringsParams.MAX_STRING_LENGTH);
	sTwo : STRING(StringsParams.MAX_STRING_LENGTH);
	sThree : STRING(StringsParams.MAX_STRING_LENGTH);
	sFour : STRING(StringsParams.MAX_STRING_LENGTH);
	sFive : STRING(StringsParams.MAX_STRING_LENGTH);
	sSix : STRING(StringsParams.MAX_STRING_LENGTH);
END_VAR
VAR
	str : STRING(StringsParams.MAX_STRING_LENGTH);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[str := F_Concat5_Large( sTwo, sThree, sFour, sFive, sSix);
F_Concat6_Large := 
	F_ConcatLarge(
		sOne,
		str
	);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat6_Large">
      <LineId Id="36" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>