<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_Concat3_Large" Id="{d074b91b-6f44-48d1-b047-26a84770af6d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat3_Large : LongString;
VAR_IN_OUT CONSTANT
   StringOne : LongString;
   StringTwo : LongString;
   StringThree : LongString;
END_VAR
VAR
   str : LongString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[str := F_ConcatLarge(StringTwo, StringThree);

F_Concat3_Large :=
   F_ConcatLarge(
      StringOne,
      str
   );]]></ST>
    </Implementation>
    <LineIds Name="F_Concat3_Large">
      <LineId Id="78" Count="5" />
      <LineId Id="23" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>