<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="F_Concat6_Large" Id="{3877e970-03ef-4a02-a195-62ac08a0495d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat6_Large : LongString
VAR_IN_OUT CONSTANT
	sOne : LongString;
	sTwo : LongString;
	sThree : LongString;
	sFour : LongString;
	sFive : LongString;
	sSix : LongString;
END_VAR
VAR
	str : LongString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[str := F_Concat5_Large( sTwo, sThree, sFour, sFive, sSix);
F_Concat6_Large := 
	F_ConcatLarge(
		sOne,
		str
	);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat6_Large">
      <LineId Id="36" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>